/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xggwjzoekueeygkdrwlp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZ3dqem9la3VlZXlna2Ryd2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MDIyNDEsImV4cCI6MjA4NTA3ODI0MX0.nzVpLNITfNXhw-ImWoN33ODZaIcSSMzWL-Zpwd0XxJU"